### ISSUE TITLE
Some Marks are not correct positioned

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Jomhuria#20]
http://tarobish.github.io/Jomhuria/#tests/collision-below-2

Alef `uni0671.fina` and Alef `uni0622.fina`.
The `uni0622.fina` Alef with Madda above is also misbehaving in combination with `uni0655` (first row in each section)

**Comment by graphicore** [comment]
Not also. The `uniF***` and `u1EE**` I wont fix in this regard, because:

**Comment by Tarobish** [comment]
i checked them all
it is a same problem, it works perfectly alone but it doesn’t when it comes with Madda or Hamza.wasl above.
or uni 0651 (shahada) it look perfect in the Anchor control window (with TashkilTashkil above or below) but as you see in the sample (with white background) it doesn’t or uni 064F.

**Comment by graphicore** [comment]
Did you attach an image? Go to: https://github.com/Tarobish/Jomhuria/issues/20 and drag it into a comment field. It seems that images don't survive email-posting.

**Comment by Tarobish** [comment]
![screen shot 2015-06-20 at 12 02 22 pm](https://cloud.githubusercontent.com/assets/8403973/8268886/8cb7a634-1747-11e5-91ee-c98841f013f6.png)
![screen shot 2015-06-20 at 12 03 03 pm](https://cloud.githubusercontent.com/assets/8403973/8268888/94671234-1747-11e5-8f94-64a3ac12e2b9.png)
![screen shot 2015-06-20 at 12 00 08 pm](https://cloud.githubusercontent.com/assets/8403973/8268889/96a1f1e0-1747-11e5-91b9-6ab014bbda75.png)
![screen shot 2015-06-20 at 12 07 22 pm](https://cloud.githubusercontent.com/assets/8403973/8268890/9934f75e-1747-11e5-821c-23281af7dde6.png)
![screen shot 2015-06-20 at 11 59 07 am](https://cloud.githubusercontent.com/assets/8403973/8268891/9bd8d020-1747-11e5-93c4-48ede1555cba.png)
![screen shot 2015-06-20 at 11 55 49 am](https://cloud.githubusercontent.com/assets/8403973/8268892/9deebb7c-1747-11e5-809f-b859424e83d9.png)

**Comment by graphicore** [comment]
Not how in the second row from the right collide. I fixed that in 8e79123b by adding a lot of `TashkilTashkilBelow` marks to the Mark characters. This is actually the only column in the table that does mark to mark positioning, that's why we don't have the problem anywhere else.

The `uni0622.fina` alef with madda above in the 6th column from the right. In the first line I reversed some normalization that took place, to get the actual uni0622.fina glyph shaped c045e6c649b4

Then for `Alef uni0622.fina` and `uni0671.fina`  , 6th row and last row from the right in the screenshot, I added the missing base anchors `TashkilAbove` and `TashkilBelow` in 4e6b5cf25

Old:

![selection_065](https://cloud.githubusercontent.com/assets/393132/8320660/1b1132dc-1a1e-11e5-8002-be20ac260cd0.png)

New:

![selection_066](https://cloud.githubusercontent.com/assets/393132/8320769/28a0bdd6-1a1f-11e5-8dcf-c87ad848be1a.png)

**Comment by graphicore** [comment]
@Tarobish The last screenshot that you posted here. That has probably also to do with missing anchors.

However, I think I fixed only mark to mark positioning below the baseline. Do we need this? Should I make one or two mark to mark test tables?

**Comment by Tarobish** [comment]
I belive, we are good. we are done with the "Alef" ;) but if you think we have to add more test table,
please do it. up to you :) we still have the same problem with position of marks (screenshot المفرد )

**Comment by graphicore** [comment]
Ok, good. We should do lazy evaluation here and close this. If anything is not working in real world scenarios, we can still fix it later. The bug tracker is open.
